### ISSUE TITLE
Route that triggered Login

### ISSUE THREAD

**Issue by polderudo** [websanova/vue-auth#104]
Is there any way to get the route that triggered an Login?
It would be nice to redirect to the link that triggered the Login after successfully login in.
(redirect in this.$auth.login)

**Comment by websanova** [comment]
Yes, I need this also. I will try to get it in soon.

**Comment by websanova** [comment]
Ok, this has been added in.

https://github.com/websanova/vue-auth#redirect

You can see some example here also:

https://github.com/websanova/vue-auth/blob/master/2.x.demo/src/components/pages/Login.vue

Hopefully it's self explanatory.

I didn't want to overdue it and force any query params. At least not for now. I think it's flexible enough so that anyone can add their own way of dealing with it. For instance via query param or silent. And also able to deal with the login, forbidden and not found redirect if they wish to..

**Comment by polderudo** [comment]
Works great. Thanks :)
