### ISSUE TITLE
Issue with refresh page.

### ISSUE THREAD

**Issue by dskozin** [websanova/vue-auth#125]
Hello!

Thank's for you GREAT job!

I have an issue with refreshing token. When i refresh page vue-auth send request to refreshData url to renew authorisation token. Request pass through jwt.refresh middleware (of Laravel 5.4) and return new Authorization header. Then vue-auth try to fetch user data, but using old token. They get 401 status, logout user and redirect to login page.

May be this happen because i using axios...

**Comment by websanova** [comment]
Yes, this is common issue. Typically it's solved with a blacklist grace
period.

In the plugin, I run a refresh as a convenience at each page refresh but it
can be at any time or interval.

The reason why it's not running sequentially is because that refresh can
get triggered at any time based on what the developer sets up. So if there
is a request that happens to fire at that same time it will be on going
issue.

There are many y scenarios so typically you can just send the grace period
or just disable the refresh and come up with some other scheme.
