### ISSUE TITLE
adding a ready event instead or in addition to ready method

### ISSUE THREAD

**Issue by darkylmnx** [websanova/vue-auth#135]
hi @websanova,

i'm encounting a disturbing issue here and i didn't find any solution.
I need to open a modal depending on user data, but the thing is, this modal is at the root of my app, so not tied to the router component, therefore using the **$auth.ready()** doesn't fit the need because it's a method i can't (in the component logic) check when the method's value changes.

A suitable thing would be to fire an event when the ready method's value changes or change the ready method to be a Vue property, so it can then be watched by Vue.

Here's an example of what i'm trying to do

```
<div id="app" :class="{'logged-in': $auth.check()}">
    <alerts></alerts>

    <router-view v-if="is_loaded && $auth.ready()"></router-view>
    <transition leave-to-class="fadeOut" leave-active-class="animated">
      <div class="site-loading app-loader" v-if="!(is_loaded && $auth.ready())"></div>
    </transition>

    <modal-base :open="modals.social_links" @close="modals.social_links = false">
      <modal-social-links></modal-social-links>
    </modal-base>
</div>
```

Here **modals.social_links** needs to be true only when : the user is logged, and the user has less than 3 social links, but, he can still close the modal, but if he reloads the page (not change route but really reload) he will get the modal again if he still matches the condition

and the problem here is that **modal.social_links" is my state, this state can be changed from anywhere so i can't do something like : 

`modals.social_links = this.$auth.ready() && this.$auth.user().links.length < 3`

because i will be false on init, while it could be true OR false when the user is gotten from the server

with and event or a vue property i could watch i'd do something like

```
modals.social_links = false;

this.$auth.$on('ready', () => {
  if (this.$auth.user().links) modals.social_links =  (this.$auth.user().links.length < 3)
})
```

I think using events is most of the time a good way to dialog between components for things "out of flow" or asyn things. Something like the jQuery ready method with a callback

**Comment by websanova** [comment]
lol, yes this is very disturbing!

Actually I tried working this out before already but it's quite complicated
because of the interceptors.

They would need to run in proper order and it's not always guaranteed.

A simple solution is to just wrap your parent component with an
auth.ready() and put your modal in there using an v-if.

Actually in my apps I just use my root component to do auth ready and
loader checks and to toggle a spinner loading screen. The v-vif has minimal
impact at this point, then I includ the actual app component on ready and
there can use the "created" method to set anything else I need ;)

Hope that solves your disturbance.

On Apr 14, 2017 5:27 AM, "darkylmnx" <notifications@github.com> wrote:

hi @websanova <https://github.com/websanova>,

i'm encounting a disturbing issue here and i didn't find any solution.
I need to open a modal depending on use data, but the thing is, this modal
is at the root of my app, so not tied to the router component, therefore
using the *$auth.ready()* doesn't fit the need because it's a method i
can't (in the component logic) check when the status (ready or not ready)
changes.

A suitable thing would be to fire an event when the ready method changes of
to make the ready be, not a method but a property, that can then be watched
by a vue component.

Here's an example of what i'm trying to do

<div id="app" :class="{'logged-in': $auth.check()}">
    <alerts></alerts>

    <router-view v-if="is_loaded && $auth.ready()"></router-view>
    <transition leave-to-class="fadeOut" leave-active-class="animated">
      <div class="site-loading app-loader" v-if="!(is_loaded &&
$auth.ready())"></div>
    </transition>

    <modal-base :open="modals.social_links"
@close="modals.social_links = false">
      <modal-social-links></modal-social-links>
    </modal-base>
</div>

Here *modals.social_links* needs to be true only when : the use is logged,
and the user has less than 3 social links, but, he can still close the
modal, but if he reloads the page (not change route, reloading) he will get
the modal again if he still matches the condition

and the problem here is that **modal.social_links" is my state, this state
can be changed from anywhere so i can't do something like

modals.social_links = this.$auth.ready() && this.$auth.user().links.length
< 3

because i will be false on init, but may be true OR false when the user is
gotten from the server

with and event or a vue property i could watch i'd do something like

modals.social_links = false;

this.$auth.$on('ready', () => {
  if (this.$auth.user().links) modals.social_links =
(this.$auth.user().links.length < 3)
})

I think using events is most of the time a good way to dialog between
components for things "out of flow" or asyn things

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/135>, or mute the thread

**Comment by darkylmnx** [comment]
yes this is what i thought of first, but this changes my design and adds markup (which in the case of modals realy a pain in the ass), my website is a full screen website, so adding markup means adding a bunch of css with some "height: 100%" everywhere etc so each extra element i can add is to avoid mostly.

Anyway, what i was saying about events was very simple, if on **$auth.watch** which seems to be your vue instance from what i understood of your code, if there you just fire an event like **$atuh.watch.$emit('loaded')** when the loaded (ready) is done anybody could catch it anywhere with **$auth.watch.$on('loaded')** and that doesn't need interceptors or so since you just fire this from place where you did **$auth.watch.loaded = true**

Now, what you said also made me think about the fact that indeed, it would be helpfull to have a callback on each "fetchUser" that is done to recalculate things based on the freshly gotten user form the server, in this case maybe interceptors are random but a simple callback would do the case.

adding something like **onFetchedUser** wich would be a function added in the options

**Comment by websanova** [comment]
Adds markup?

You are worried about...?

```
<div>
<div v-if="$auth.ready()">
    .... Everything goes in here
</div>

<div v-if="!$auth.ready()">
    loading...
</div>
</div>
```

You could even just make it computed property if you really want it short.

It's pretty much the same as any event code you would write.

The problem with the auth.ready event is that it would have to be the
initializer for the interceptors.

Right now they run before your root component is even called so it will
miss the change since your watch is not even there yet.

I suppose this could be done, but not sure if this will have other impacts.

**Comment by websanova** [comment]
btw, technically if you want to watch it you could put a watch on
`$auth.watch.loaded`.

On Apr 15, 2017 09:48, "Rob" <rob@websanova.com> wrote:

Adds markup?

You are worried about...?

```
<div>
<div v-if="$auth.ready()">
    .... Everything goes in here
</div>

<div v-if="!$auth.ready()">
    loading...
</div>
</div>
```

You could even just make it computed property if you really want it short.

It's pretty much the same as any event code you would write.

The problem with the auth.ready event is that it would have to be the
initializer for the interceptors.

Right now they run before your root component is even called so it will
miss the change since your watch is not even there yet.

I suppose this could be done, but not sure if this will have other impacts.

**Comment by darkylmnx** [comment]
This is what I did before writing this issue haha, but I wanted us to
discuss on a better way to do this but If you think there's no need for an
event, fair enough.

Have thought of something to know whenever a new fetchuser is done ? Is the
$auth.user() is not a prop too
