### ISSUE TITLE
How to catch if token is expired?

### ISSUE THREAD

**Issue by akaNightmare** [websanova/vue-auth#161]
Hi,
I can't figure out how to catch exception when refresh token request returns 401 Http Status?

**Comment by websanova** [comment]
Should work automatically, what version are.you using?

**Comment by akaNightmare** [comment]
@websanova `"@websanova/vue-auth": "2.11.0-beta",`, also I want to make something like this `store.commit('USER_CLEAR')` if auth token refresh result is 401.

**Comment by websanova** [comment]
Well you can just write your own driver then. Just customize one of the
ones here for example Bearer.js

https://github.com/websanova/vue-auth/blob/master/drivers/auth/bearer.js

For the 401 I guess you are using Axios. There was a bug reported there for
how the intercept for errors is created, but I don't use Axios so have't
really had a chance to play with it.

Otherwise the vue-resource driver should be working:

https://github.com/websanova/vue-auth/blob/master/drivers/http/vue-resource.1.x.js#L21

**Comment by websanova** [comment]
Issue with axios intercept should be resolved in latest.

**Comment by akaNightmare** [comment]
@websanova thank you.
Last question: can rewrite/override fetchUser (I want to user GraphQL)?
