### ISSUE TITLE
Issue setting router in the alternative way

### ISSUE THREAD

**Issue by blaluc** [websanova/vue-auth#162]
In the documentation it is said:
"
NOTE: If you do not set your router as Vue.router = new VueRouter() then you will need to feed the router in directly through the options. Also true for http.

var router = new VueRouter();
Vue.use(Auth, {
    router: router,
    http: http
});
"
If I try to do so, it doesn't work (utils.js?92c3:3 Uncaught RangeError: Maximum call stack size exceeded
    at isObject (eval at <anonymous> (app.js:2464), <anonymous>:3:22))

Do you confirm that it's possible to pass the VueRouter instance instead of the driver?

(I'm using the latest vue-router 2)

Many thanks

**Comment by websanova** [comment]
Ah ya, because I have an deep copy on that object passed in. Will need to
set an ignore for those.

But really should be part of the driver somehow because of the dependency
there.

Hos do you have it stored now? I dont think it's a big deal to set
Vue.router = router. Not gonna change much except add a few characters.

**Comment by websanova** [comment]
Actually I answered that incorrectly. You should never be setting the router like this at all and this parameter does not exist.

The `router` there is for the driver not for the vue-router.
