### ISSUE TITLE
Reference Vue.router

### ISSUE THREAD

**Issue by tho068** [websanova/vue-auth#193]
I think the Vue.router reference should really be Vue.$router as this is the way it is by default in Vue 2 using Vue-router

Is there any reason why it is not?

**Comment by websanova** [comment]
Well it's really just a race condition here.

There is nothing magical that happens, it really just creates the intercept for `beforeEach` on the router. So yes actually this can be created at any time. But if you don't do it before the app fires it's first route call then it will miss meaning we would need some manual intervention. Like a `$auth.init()` call in the root component.

I've wanted to actually get rid of the `Vue.router = new Router` thing for a while. But I think the issue was that I was never able to find a hook for this where `$router` existed.

The only way I found around it was to do some kind of `$auth.init()` call which would be called in the root component.

**Comment by tho068** [comment]
Yes, could not find a documented hook either. Havent looked through the source of vue-router though so I would not really know.

Thanks for the answer though.
