### ISSUE TITLE
Refresh bad status

### ISSUE THREAD

**Issue by alanrivetta** [websanova/vue-auth#199]
Situation:
User correctly logged.
Close the application.
It opens the other day (Refresh interval:30 minutes),  you see this:

GET http://XXX/user/refresh?token=NDZmNmI2ZmUxNjcxZTNjODBhMjU1YjlhNzg2MWY5ODkwMDA0ZTAzNTIxZTgzNGYyYjU5ZDJiYjkzN2M0OTBhMA 400 (Bad Request)

What would be the default behavior in the plugin?

Because this $ auth.ready () is false and in localStorage I still see the auth_token_default.

Is it my responsibility to clean the token?

**Comment by websanova** [comment]
You're just not catching the j valid token case. Look at the invalid token
function here. But default it's made to handle 401, but you can override
this.

https://github.com/websanova/vue-auth/blob/master/drivers/http/vue-resource.1.x.js


On Jul 20, 2017 05:52, "alanrivetta" <notifications@github.com> wrote:

Situation:
User correctly logged.
Close the application.
It opens the other day (Refresh interval:30 minutes), you see this:

GET http://XXX/user/refresh?token=NDZmNmI2ZmUxNjcxZTNjODBhMjU1Yj
lhNzg2MWY5ODkwMDA0ZTAzNTIxZTgzNGYyYjU5ZDJiYjkzN2M0OTBhMA 400 (Bad Request)

What would be the default behavior in the plugin?

Because this $ auth.ready () is false and in localStorage I still see the
auth_token_default.

Is it my responsibility to clean the token?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/199>, or mute the thread
