### ISSUE TITLE
Cannot get register request response (axios)

### ISSUE THREAD

**Issue by nkostadinov** [websanova/vue-auth#206]
I'm trying to get the response of a failed register request:

```
                    this.$auth.register({
                        data: this.user, // Axios
                        error: function(res) {
                            console.log(res);
                        },
                        autoLogin: true,
                        rememberMe: true
                    })
```
But I only get a string representing the error:

`Error: Request failed with status code 422`

Should this param be the response object ?

**Comment by websanova** [comment]
Lol, this is axios, try res.response

On Aug 2, 2017 9:46 PM, "Nikola Kostadinov" <notifications@github.com>
wrote:

I'm trying to get the response of a failed register request:

                    this.$auth.register({
                        data: this.user, // Axios
                        error: function(res) {
                            console.log(res);
                        },
                        autoLogin: true,
                        rememberMe: true
                    })

But I only get a string representing the error:

Error: Request failed with status code 422

Should this param be the response object ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/206>, or mute the thread

**Comment by nkostadinov** [comment]
you are right, my mistake :) 10x for the help and the great extension .
