### ISSUE TITLE
Strange issue in v2.16.1-beta

### ISSUE THREAD

**Issue by Kuchiriel** [websanova/vue-auth#222]
If I use that driver 
` auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),`

Or 
```
 auth: {
    request (req, token) {
      this.options.http._setHeaders.call(this,
        req, {
          Authorization: `Bearer ${token}`
        })
    },
    response ({data}) {
      // Get Token from response body
      return data
    }
  },
```
The error on the image bellow occurs.

Managed to escape the error and login, by removing token from second parameter (so I guess must be something to do with this parameter) 

```
auth: {
    request(req) {
      this.options.http._setHeaders.call(this,
        req, {
          Authorization: `Bearer `
        })
    },
    response({
      data
    }) {
      // Get Token from response body
      return data
    }
  },
```
But browser keeps logging this
`xhr.js?ec6c:178 GET http://localhost:8080/auth/user 404 (Not Found)`

![https://i.imgur.com/GAnPvci.png](https://i.imgur.com/GAnPvci.png)

Basic driver works fine. (but, naturally, need to modify the backend api)

Thanks!

**Comment by websanova** [comment]
Did you set the other drivers as well?

**Comment by Kuchiriel** [comment]
Yes, these.
``` 
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'), // eslint-disable-line
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'), // eslint-disable-line
```

**Comment by websanova** [comment]
Hmm, not sure, but why is the token an HTML document?

**Comment by Kuchiriel** [comment]
@web This is why is 'strange'.

**Comment by websanova** [comment]
Can you verify your back end is providing proper token via direct request
using some REST client perhaps?

On Aug 11, 2017 13:04, "Matheus Almeida" <notifications@github.com> wrote:

@web <https://github.com/web> This is why is 'strange'.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/222#issuecomment-321732582>,
or mute the thread

**Comment by guilhermewaess** [comment]
Looks like your back-end is returning a html response.

**Comment by Kuchiriel** [comment]
As I said.


> Managed to escape the error and login, by removing token from second parameter (so I guess must be something to do with this parameter)
> 
> Basic driver works fine. (but, naturally, need to modify the backend api)


That means I can actually receive the token, if I remove the second parameter. 

This appears to be, something sending a xhr error wrapped in html to the request function.

**Comment by jionlab205** [comment]
@Kuchiriel , I faced same error and same error messages while I deploy vue-auth.  For My case, I found the symptoms. It caused by login again while already loged in.  Then  the key in the local storage that contains the html parts of error message. And it may cause error of next login request.  This strange key  only deleted after restart chrome itself.  So I "auth: false" for /login route. Hope this help.

**Comment by websanova** [comment]
Well, if you have some dud key, you could also just run `$auth.logout()` which should clear everything.

**Comment by Kuchiriel** [comment]
I had to do this, now its working.

```
Vue.use(VueAuth, {
  auth: {
    request(req, token) {
      this.options.http._setHeaders.call(this,
        req, {
          Authorization: `Bearer ${token}`
        })
    },
    response({
      data
    }) {
      // Get Token from response body
      return data
    }
  },
  // auth: require('@websanova/vue-auth/drivers/auth/bearer.js'), // eslint-disable-line
  loginData: {
    url: `${defaultURL}/v1/login`,
    fetchUser: false
  },
  refreshData: {
    url: `${defaultURL}/v1/login`,
    enabled: false
  },
  fetchData: {
    url: `${defaultURL}/v1/login`,
    enabled: false
  },
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'), // eslint-disable-line
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'), // eslint-disable-line
})
```
