### ISSUE TITLE
Axios request interceptor doesn't seem to kick in after hard refresh

### ISSUE THREAD

**Issue by abishekrsrikaanth** [websanova/vue-auth#229]
I overrode the `bearer.js` on to my project copying the existing `bearer.js` with the below code because the authorization token and the refresh token from my oAuth Server are returned on the HTTP Response and not the Response Headers.

```
module.exports = {

  request: function (req, token) {
    console.log('Request Interceptor called');
    this.options.http._setHeaders.call(this, req, {Authorization: 'Bearer ' + token});
  },

  response: function (res) {
    let token = res.data.access_token;
    console.log('Response Interceptor called');
    if (token) {
      token = token.split(/Bearer\:?\s?/i);

      return token[token.length > 1 ? 1 : 0].trim();
    }
  }
};

```

After I login, the request interceptor from the above does seem to get called and add the Bearer token is set on the Request Header. But for some reason, when I hard refresh the page, the request interceptor does not get called and I get logged out because `authRedirect` is setup on the `vue-auth` setup. 

I am adding the setup code below just to make sure I am not missing anything

```
import Vue from 'vue'
import router from './router'
import {sync} from 'vuex-router-sync'
import axios from 'axios';
import VueAxios from 'vue-axios';
import VueAuth from '@websanova/vue-auth'
import AuthBearer from './utils/oauth/bearer'
import httpDriver from '@websanova/vue-auth/drivers/http/axios.1.x'
import routerDriver from '@websanova/vue-auth/drivers/router/vue-router.2.x'

sync(store, router)

const app = new Vue({
  router,
  store,
  ...App
})


Vue.use(VueAxios, axios);

Vue.axios.defaults.baseURL = config.API_ROOT;

Vue.router = router;
Vue.use(VueAuth, {
  auth: AuthBearer,
  http: httpDriver,
  router: routerDriver,
  tokenDefaultName: 'auth_token',
  tokenOtherName: 'auth_token',
  authRedirect: '/auth/login',
  forbiddenRedirect: '/auth/403',
  notFoundRedirect: '/auth/404',
  tokenStore: ['localStorage', 'cookie'],
  _invalidToken: false,
  refreshData: {
    url: '/clients/web/admin/refresh',
    method: 'POST',
    enabled: false,
    interval: 60 * 5
  }
});

export {app, router, store}
```

@websanova, could you clarify or look into why I may be facing both these issues?

**Comment by websanova** [comment]
Not sure,

Seems.you are describing many issues here. Is this just all on single login
page?

Can you verify try api is fully working by making direct calls.

Also verify in the dev tools those calls are being made with proper data.

You should see the requests being made and what's there.

On Aug 25, 2017 06:12, "Abishek R Srikaanth" <notifications@github.com>
wrote:

I overrode the bearer.js on to my project copying the existing bearer.js
with the below code because the authorization token and the refresh token
from my oAuth Server are returned on the HTTP Response and not the Response
Headers.

module.exports = {

  request: function (req, token) {
    console.log('Request Interceptor called');
    this.options.http._setHeaders.call(this, req, {Authorization:
'Bearer ' + token});
  },

  response: function (res) {
    let token = res.data.access_token;
    console.log('Response Interceptor called');
    if (token) {
      token = token.split(/Bearer\:?\s?/i);

      return token[token.length > 1 ? 1 : 0].trim();
    }
  }
};


I am having 2 issues and am not sure if it is because of overriding this js:

   1. The request interceptor never seems to be getting called on the above
   js. I assume the request that you override never gets called. I tested this
   by adding console.log and it never gets called, but the response
   interceptor does get called.
   2. After I login, the request interceptor from the package code (not the
   one I overrode) does seem to get called and add the Bearer token is set on
   the Request Header. But for some reason, when I hard refresh the page,
   neither the base request interceptor not the one that I overrode gets
   called and I get logged out because authRedirect is setup.

I am adding the setup code below just to make sure I am not missing anything

import Vue from 'vue'
import router from './router'
import {sync} from 'vuex-router-sync'
import axios from 'axios';
import VueAxios from 'vue-axios';
import VueAuth from '@websanova/vue-auth'
import AuthBearer from './utils/oauth/bearer'
import httpDriver from '@websanova/vue-auth/drivers/http/axios.1.x'
import routerDriver from '@websanova/vue-auth/drivers/router/vue-router.2.x'

sync(store, router)

const app = new Vue({
  router,
  store,
  ...App
})


Vue.use(VueAxios, axios);

Vue.axios.defaults.baseURL = config.API_ROOT;

Vue.router = router;
Vue.use(VueAuth, {
  auth: AuthBearer,
  http: httpDriver,
  router: routerDriver,
  tokenDefaultName: 'auth_token',
  tokenOtherName: 'auth_token',
  authRedirect: '/auth/login',
  forbiddenRedirect: '/auth/403',
  notFoundRedirect: '/auth/404',
  tokenStore: ['localStorage', 'cookie'],
  _invalidToken: false,
  refreshData: {
    url: '/clients/web/admin/refresh',
    method: 'POST',
    enabled: false,
    interval: 60 * 5
  }
});

export {app, router, store}

@websanova <https://github.com/websanova>, could you clarify or look into
why I may be facing both these issues?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/229>, or mute the thread

**Comment by abishekrsrikaanth** [comment]
The issue is about the request not using the request interceptor after a hard page refresh. I am able to use my oAuth Endpoints with the vue-auth package and they the tokens bearer tokens correctly and I get the correct responses until I hard refresh the page and the request interceptor doesn't invoke. I hope that clarifies

**Comment by websanova** [comment]
Not sure, depends what you're doing on this page. Why are you expecting it
to invoke?

Need details.

**Comment by abishekrsrikaanth** [comment]
The request interceptors of the `axios` driver attach the token to the headers. They stop doing that after you refresh the page.

**Comment by romil-officetroops** [comment]
@abishekrsrikaanth I am facing the same issue. How did you fix this?
