### ISSUE TITLE
auth/refresh redirect after backend server is down (Network Error)

### ISSUE THREAD

**Issue by houzw** [websanova/vue-auth#246]
If my backend is down and webpack-dev-server is still running, `auth/refresh` will get a `net::ERR_CONNECTION_REFUSED` error, i.e. `Network Error`. I want it redirect to an error page and show a user friendly message, how can I do that?
thx.

**Comment by websanova** [comment]
How about an interceptor??

This really has nothing to do with vue-auth.

Any request would get error ;)

On Sep 13, 2017 01:01, "houzw" <notifications@github.com> wrote:

If my backend is down and webpack-dev-server is still running, auth/refresh
will get a net::ERR_CONNECTION_REFUSED error, i.e. Network Error. I want it
redirect to an error page and show a user friendly message, how can I do
that?
thx.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/246>, or mute the thread

**Comment by houzw** [comment]
If I disable auth/refresh,  interceptor works well, if not, it will continuously make request to the backend server, so it can not redirect to error page. 
Here is my interceptor code:
```javascript
axios.interceptors.response.use(
  response => {
    return response;
  },
  error => {
    if (!error.status) {
      //Network Error
      router.push({ path: '404'})
      console.log(error);
    }
     return Promise.reject(error);
  });
```
After read doc again, I should try to refresh token manually.

Thanks very much!
