### ISSUE TITLE
Can we have a default hook after refresh?

### ISSUE THREAD

**Issue by Rockson** [websanova/vue-auth#287]
I don't want to refresh the token every time the user reloads the page or changes route because I feel it's too bad.
So I override the default tokenExpired function
This is my app workflow:
* After login the app stores the expiration of the token in localstorage  (so I can refresh it before it expires)
* When the expiration is met, the function tokenExpired will return true so vue-auth will refresh.
* After refresh I need to reset the expiration of the token in the localstorage

That's why I need the after refresh hook.
However I'm not sure about this approach, should I refresh the token every time route changes, user reload page, API call instead?__

**Comment by websanova** [comment]
You can set the refresh enabled flag to false. And call it manually with
$auth.refresh() however you like.

On Nov 13, 2017 3:50 AM, "Rockson" <notifications@github.com> wrote:

I need to set a default hook after refresh.
I don't want to refresh the token every time the user refresh the page or
changes route because I feel it's too bad.
So I override the default token expired function
This is my app workflow:

   - After login the app stores the expiration of the token in localstorage
   (so I can refresh it before it expires)
   - When the expiration is met, the function tokenExpired will return true
   so vue-auth will refresh.
   - After refresh I need to reset the expiration of the token in the
   localstorage

That's why I need the after refresh hook.
However I'm not sure about this approach, should I refresh the token every
time route changes, user reload page, API call instead?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/287>, or mute the thread

**Comment by Rockson** [comment]
Yeah that would do it. Thanks!
