### ISSUE TITLE
Question: Redirect after login

### ISSUE THREAD

**Issue by polderudo** [websanova/vue-auth#303]
How can one redirect to an special url if the user logged in? I need to handle some extra information (user-must-change-password) after the user is logged in and the data is fetched, but i can't get the this.$auth.ready(function ()) work. So normaly the user would be redirected to 'home' and if the flag is set i'd like to redirect to a different page

**Comment by websanova** [comment]
Ughh, did you try redirect?

On Dec 19, 2017 05:27, "MyProfile" <notifications@github.com> wrote:

How can one redirect to an special url if the user logged in? I need to
handle some extra information (user-must-change-password) after the user is
logged in and the data is fetched, but i can't get the
this.$auth.ready(function ()) work. So normaly the user would be redirected
to 'home' and if the flag is set i'd like to redirect to a different page

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/303>, or mute the thread

**Comment by polderudo** [comment]
Do you have a short example for this? Using` redirect: {name: redirect ? redirect.from.name : 'account'},` right now, but i don't know how to use this on the success event...

**Comment by websanova** [comment]
$auth.login({
    redirect: ...
})

Just check th docs ;)

**Comment by polderudo** [comment]
Oh man. That was easy, thanks ....
But i think this is not enough. I'll have to use `router.beforeEach((to, from, next)` in order to redirect to the "change password" page. If not, the user could just enter a valid url and could pass over the functionality...

**Comment by websanova** [comment]
lol, check the docs man

you can set auth parameter on the routes, it's all in there.

**Comment by polderudo** [comment]
Hey. I hopefully  just got that wrong ... but let me explain what i try to achive :)
1) An admin resets a users password. The backend will set a field must_change_password in the database
2) This user later logges into the application. I use `this.$auth.login` therefore 
3) `$auth.success() `is called
4) vue-auth.fetchData is called
5) Now i have to check the field user_must_change_password, because this will be fetched with the vue-auth.fetchData method 

Of course all my routes are protected with meta: { auth: true } but the user IS now logged in, so he will be able to just change the url in the browser and he will reach parts that app, he should not, because he did not change the password yet. Thats why i think i have to use `router.beforeEach((to, from, next)` but i might be wrong.

**Comment by websanova** [comment]
ok, well that's just some regular app level logic then.

I guess you can do a router intercept for redirect. In the beforeEach you
would have to use `Vue.auth.user();`

You could also use `$auth.ready(function() {});` callback in some root
component.

**Comment by polderudo** [comment]
I'll try the intercept.
Btw. many thanks for the lib... and that you take time to answer questions.
