### ISSUE TITLE
IE and Edge: On page refresh the user going back to login page

### ISSUE THREAD

**Issue by akomarovsky** [websanova/vue-auth#309]
Hi,
great job on the package.

I have an when using IE 11 and Edge. When you refresh the page the user is kicked back to the login page.
I managed to debug a bit and saw that at some point after the page refresh the default_auth_token disappears from localStorage. I couldn't find what caused it.

I also use the $auth.ready correctly.

In chrome and firefox, it works perfectly.

**Comment by websanova** [comment]
Are you in some incognito mode?

**Comment by akomarovsky** [comment]
No. Regular session

**Comment by websanova** [comment]
Did you try clearing cookies?

**Comment by pkraus109** [comment]
I am having the exact same issue. Chrome, FF everything just works. In IE 11 and Edge a page fresh causes the token to be removed from localStorage.

I have developing in chrome and am approaching a product launch. Was testing in other browsers and then got hit with this. I can't seem to see any issues.

Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
  refreshData: {enabled: false},
});

Vue.auth.login({
        method: 'post',
        data: {email: payload.email, password: payload.password, rememberMe: true},
      }).catch(error => {
        console.log('error happened');
        console.log(error);
      })

Open IE, go to page, login, view localStorage default_auth_token is present.
Hit F5
User gets logged out.
Vuew localStorage and default_auth_token is gone.

Exactly the same in IE.

I am not doing anything custom with your plugin other then disabling the refesh since we don't use them.

HELP

**Comment by pkraus109** [comment]
I ... HATE ... IE

If an cooking has a domain of localhost (doesn't have <sub.server.com> (three dot domain) then IE and Edge just let it fall through without an error. Cookie is not saved and you have no idea why.

cookie.js
```
function setCookie (name, value, timeOffset) {
        var domain = this.options.cookieDomain(),
            expires = (new Date((new Date()).getTime() + timeOffset)).toUTCString();

        if (domain === 'localhost'){
          document.cookie = name + '=' + value + '; Expires=' + expires + '; Path=/;';
        }else{
          document.cookie = name + '=' + value + '; Expires=' + expires + '; Path=/; Domain=' + domain + ';';
        }
        // document.cookie = name + '=' + value + '; Expires=' + expires + '; Path=/; Domain=' + domain + ';';
    }
```

this took me all day to trace through your plugin but now i actually understand how it all works. I am normally a backend python developer so this was enlightening.
