### ISSUE TITLE
Using this with 2FA

### ISSUE THREAD

**Issue by jclee100** [websanova/vue-auth#369]
I need this to work with TOTP 2FA. So when user logs in with email and password and has 2FA enabled, the user will be prompted to enter the OTP code.

How can I make this.$auth.login() handle a custom response such that it doesn't log the user in?

If there's no way to do this, I will manually post to my login path to handle the response. Then, I will use the login method -- but this will take 2 calls even if the user has 2FA disabled.

**Comment by websanova** [comment]
Not, sure about your setup, but I would imagine it's just a custom driver.

**Comment by komirad** [comment]
I am using your drivers as follows. Maybe I can modify the bearer.js's response method, but it doesn't feel like a very clean way to handle this and I still need a way to pass in a callback so that my component can pop-up a prompt.

```
Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/axios.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
});
```

I could return a HTTP error from the server but that doesn't seem like the right approach.

**Comment by websanova** [comment]
I said custom driver.

Should not be too hard to setup. Actually the plug-in only logs in when it
has a valid token. The login method doesn't actually log a user in. But
depends on the setup.

So it's two questions, how do your auth tokens work. And what happens if
anusr refresh, they have to start over again?

If it's just basic jwt bases auth, I would imagine you could just call
login twice. The first response would just be some kind of "ok" response to
trigger the second login, which would then send all the required info and
do a proper login.

Nothing really special dude ;)

**Comment by komirad** [comment]
Sorry, I wasn't clear. What I meant by modifying was creating a custom driver referencing existing drivers since it already works.

It's JWT bearer if that's what you are asking. And they don't have to start over if refreshed. The token is saved into session.

And yes that's the approach I thought of too. I am just unclear on how to do this.

The `this.options.loginData` in auth driver's response's context doesn't contain the custom data specified when calling the login method. i.e. I can't access the `requireOtp()` callback from auth driver.
```
this.$auth.login({
    data: {
        email: this.email,
        password: this.password
    },
    requireOtp() {
        this.promptOtpForm();
    },
...
```

The only way I found is to do the following. Doesn't seem very proper but it works.
```
// In my Login.vue
this.$auth.requireOtp = () => {
        this.promptOtpForm();
};
this.$auth.login({
...

// In my custom auth driver
response: function (res) {
    var headers = this.options.http._getHeaders.call(this, res),
        token = headers.Authorization || headers.authorization;

    if(res.data.otp_required && this.requireOtp) {
        this.requireOtp();
    }

    if (token) {
        token = token.split(/Bearer\:?\s?/i);

        return token[token.length > 1 ? 1 : 0].trim();
    }
}
```

Kindly let me know if there's a better way.

**Comment by websanova** [comment]
Well you can call your function on success can't you?

And the auth drivers are like two lines of code, just look at the source ;)
