### ISSUE TITLE
Feature Request : Support for permissions ( A more specific version of roles) 

### ISSUE THREAD

**Issue by nonsocode** [websanova/vue-auth#391]
A lot of Systems work on the Role - Permissions security model.

Right now, Roles have been implemented and it works fine. However, there are certain scenarios where a user might have a role but not have a specific permission to do something that other members of that role might have permission to do.

It would be nice to have support for both permission and roles.

**Comment by websanova** [comment]
Example please...

**Comment by rodrigoo-csantos** [comment]
Hi, websanova

Roles define or group the permissions.

role: manager
permissions: create-posts, edit-posts, delete-posts.

It is also possible to grant a user a permission without a role.

user: name.lastName,
roles: {manager},
permissions: {all permissions linked to role manager + permissions granted directly to the user eg: report-post}

**Comment by websanova** [comment]
Ok,

So here is what I've done for now. Essentially you just wanna check a different parameter on the user other than the `rolesVar` which is set to `roles` by default.

So first off, I've updated the `$auth.check()` method to accept a second optional `key` param. So basically all the same rules apply accept you can check another field.

(make sure to grab the latest `2.21.14-beta`).

```
$auth.user().permissions = ['report-post'];

$auth.check('report-post', 'permissions'); // true
```

You can of course just make some shortcut in your bootstrap or config or whatever.

```
Vue.auth.perms = function (perm) {
    return this.options.check.call(this, perm, 'permissions');
};
```

And then just follow the same compare logic:

````
$auth.perms('report-post');
$auth.perms(['report-post']);
```

So that pretty much covers most of it. The other part is of course with the routes. But for now I don't think I wanna mess with that. There are gonna be too many different setups with permissions, even roles alone has had lots of changes.

Also, there will be issues with redirects and which has precedence, so I just don't wanna go there. If a redirect is required, I think it can just be handled with a simple router intercept.

**Comment by nonsocode** [comment]
Thanks. This is great

**Comment by rpgwhore** [comment]
Just wanted to say, I came here looking for the same thing! Glad someone spoke up, because this was preventing me from using this package :D
