### ISSUE TITLE
how to tell when jwt token is impersonated on the backend side?

### ISSUE THREAD

**Issue by vesper8** [websanova/vue-auth#399]
I'm using this awesome library and want to use the built-in impersonate functionalities.

But on my laravel backend, there are certain actions I don't want performed when I am impersonating a user for testing purposes, such as triggering emails or updating certain data.

I use a simple middleware "jwt.auth" on the laravel side, Could you please explain how can I differentiate regular jwt tokens from impersonated ones (that an admin user, me, would be using) ?

**Comment by websanova** [comment]
Well, this would be done with some role or permission on the user. The token simply tells you which iser it is.

**Comment by vesper8** [comment]
hrmm.. would you mind elaborating a bit more please @websanova 

before when I was doing impersonation with Laravel, it was easy to add something to the session while impersonation was "active". But since with jwt tokens everything is stateless, and as far as I know it isn't possible to attach something extra when the jwt token is being passed, then how can I tell a real user from an impersonated user?

**Comment by websanova** [comment]
Did you check the docs at all??

$auth.impersonating()

**Comment by vesper8** [comment]
No need to be rude, I did check the docs and was aware that it's very easy to determine if impersonating or not on the client side, that wasn't my question. I was inquiring if there was a way to tell the difference between an impersonated user or not on the server's side. I am migrating from an app that doesn't use stateless and jwt to one that does, and I previously had a bunch of checks on the server side to not perform certain actions when a user was being impersonated. Moving these conditionals to the client side is what I was trying to avoid and simply wondered if there was a cleaner way to handle this then either add conditionals on the client-side or pass some kind of "is_impersonating" parameter to the rest api

**Comment by websanova** [comment]
I already answered that :-)

Why would your API need to know if it's impersonating? You simply get a request and it gives you a user object. That user independently should have access to specific parts of the API via a role or permissions.

Anything else doesn't make much sense. I could just stuff my token with impersonating data for access which would be security issue.

**Comment by vesper8** [comment]
@websanova Hi again.. so I started implementing my impersonating logic and I see from one of your demos that you let your API know whether the client side is impersonating or not, like this:

https://github.com/websanova/vue-auth/blob/master/demos/2.x/src/components/pages/Account.vue#L65

I would have preferred to be able to add this parameter to every request, because I want my API to function the same whether you're impersonating or not but I don't want certain things to persist to the database if impersonating

basically I want to know if there's an easy way to add this param to every call, similar to how you add the auth token to every axios call

and perhaps even more importantly.. I want to know if impersonation is turned on at the moment where the user is fetched. I tried to do this inside my auth.js file:

```
  fetchData: {
    url: '/api/auth/user',
    method: 'GET',
    params: {
      impersonating: this.$auth.impersonating(),
    },
    enabled: true,
  },
```

but looks like I don't have access to the $auth object yet in this scope

the reason I need to do this is because I have a method on my backend that updates the "last_seen_at" date and I like to do this on the /auth/user, but I don't want this to be updated if I'm impersonating one of my users for testing

would very much appreciate an answer. Thanks

**Comment by websanova** [comment]
Ah,

This is quite two different things. In the link you sent this is not a parameter. It's a flag that actually runs the request as the initially logged in admin user and not the currently impersonated user. So basically it's just sending the admin token instead of the impersonated users token.

You could, set some parameter along with requests, but I would be weary of granting access to anything in your api with this since it can of course be faked quite easily.

I think it might depend how your API is setup. Personally I prefer just running with the impersonating flag toggled on and then keep my API generic like /users/:id/update rather that /users/me update. So it's based on access to the object/model instead of based on currently logged in user.

In fact, I try to avoid any routes that require currently logged in user id. I always make sure it's based on the model I'm requesting the action on.

With that said, in cases like this I try not to complicate things too much. For a least seen I would just setup some 30 minute interval to update my api on a separate route.

~~~
setInterval(function () {
   if ( ! this.$auth.impersonating())
        this.$http({
            method: 'put',
            url: 'users/' + this.$auth.user().id + '/active'
        })
    }
});
~~~

This would even give you more accurate "last active" data also. It could even be put into some kind of http intercept and run on every x number of requests. Something like that.

I think the only other way to stuff it into the API would be to include some kind of secondary param on each request in the header. Like `Admin-Authorization: token....`. But then you need to validate this token each time to make sure there is a secondary admin user otherwise things can just be faked.

Depends how much you are worried about things though. But otherwise a simple intercept in vue-resource or axios should work fine.
