### ISSUE TITLE
Token in response

### ISSUE THREAD

**Issue by dgrubelic** [websanova/vue-auth#42]
Hi there,

I'm trying to implement this lib to my Vue2 app. Basically, i have a problem with collecting token from response since my login response looks like this (token is located in `response.data.token`):

```
{
  data: {
    ...
    token: "......"
  }
}
```

Changing the response is pretty much not an option. Any suggestions? (please let me know if you need any more info)

**Comment by websanova** [comment]
Hey, so I've just done an update for how the auth drivers works. Make sure you get the latest `v1.4.0-beta` release. Because this is a bit non standard you will need to create a custom auth driver. You can check out the [Authentication docs](https://github.com/websanova/vue-auth#authentication), it should look something like in the example there.

~~~
authType: 'custom1',

custom1Auth: {
    request: function (req, token) {
        req.headers.set('Authorization', token);
    },
    response: function (res) {
        return (res.data.data || {}).token;
    }
}
~~~

The response part should handle the token setup you have. Not sure how you're sending the token in the request though.

**Comment by dgrubelic** [comment]
Thank you for your response. I actually managed to implement this by extending `responseIntercept` and `bearerAuth` (since this API i'm using has `Authorization: JWT abcde123` token format). 

But since this is much more elegant solution, i updated to a new version.

**Comment by websanova** [comment]
Ya, I think it's better than hacking the internal functions :p

**Comment by dgrubelic** [comment]
I agree, but previous solution was the only way to implement your lib into my app. Now it's fixed 😄 

Closing....
