### ISSUE TITLE
Is this perfectly working on latest tymon/jwt-auth?

### ISSUE THREAD

**Issue by paulfolio** [websanova/vue-auth#426]
When i use `tymon/jwt-auth: 0.5.12` it is working but after i migrated to latest  version of `jtymon/jwt-auth": "^1.0.0-rc.2` it is not working. It stuck on login it cant fetch the login user. 

![vue auth](https://user-images.githubusercontent.com/8663669/44823193-964ffe80-ac31-11e8-834e-e333b00634bd.PNG)

**Comment by websanova** [comment]
Well the plug-in is independent of the back end, as long as you get a token
back it will be fine.

**Comment by websanova** [comment]
Yes, looks fine, otherwise you can set redirect many ways after login.

**Comment by vesper8** [comment]
I was having a problem too after upgrading from ```tymon/jwt-auth: 0.5.12``` to ```tymon/jwt-auth: 1.0.0-rc.3```

I followed the guide to install the new 1.0 version properly and then all of a sudden my login stopped working on the vue side (using this package)

turns out the problem was easy to resolve.

Previously on the laravel side the login function was returning the authorization token as a header, but following the 1.0 guide it is now returning it as a parameter

rather than create a custom driver on the vue side, I just reverted to how it was before

so instead of

```
    protected function respondWithToken($token)
    {
        return response()->json([
            'access_token' => $token,
            'token_type' => 'bearer',
            'expires_in' => auth()->factory()->getTTL() * 60
        ]);
    }   
```

I just went back to using

```
    protected function respondWithToken($token)
    {
        return response([
            'status' => 'success'
        ])
        ->header('Authorization', $token);
    }   
```

for both the login and refresh methods, and now all is working as it was before again
