### ISSUE TITLE
using with vue-cli cordova plugin and Facebook auth

### ISSUE THREAD

**Issue by vesper8** [websanova/vue-auth#456]
currently my pwa makes use of this package with facebook auth and works wonderfully

first it gets a token from Facebook

then it sends that to my rest api, a user is created if it doesn't already exist, and then a jwt token is returned from that user and thus my pwa is authenticated via jwt and Facebook auth

now I'm looking to extend this codebase and make it work with cordova via this plugin https://github.com/m0dch3n/vue-cli-plugin-cordova/issues

I've already had luck using this plugin for another app that uses this package and JWT, but this is the first time I'm trying to use it with an app that depends on Facebook login

My very first try failed and I assume it's because the callback url is wrong.. since there isn't really a callback url since we're dealing with an app this time.

My question is.. do you think it's possible to make it work with this package alone or do I have to use a cordova plugin such as this one https://github.com/jeduan/cordova-plugin-facebook4 and handle the sign-in process differently for the users on android/ios ?

**Comment by websanova** [comment]
Sorry, I don't any experience with Apache Cordova.

I can say this plugin is definitely designed as a SPA style. I haven't really tried using it with SSR style apps, something like Vuex or Quasar. It's on my radar to finally play with that and try to at least get it working with Vuex. But that could be another month before I really have time to sort it out.

Also I'm planning to update things quite a bit with this plugin, so that will come first.
