### ISSUE TITLE
$auth.user() undefined on a page with params

### ISSUE THREAD

**Issue by Nick-Case** [websanova/vue-auth#476]
Pretty much pulling my hair out on this, I've got a simple SPA in Vue set up, after following [this tutorial (and the 2nd part)](https://codebriefly.com/laravel-jwt-authentication-vue-ja-spa-part-1/) and it works a treat....

...Until I access or refresh the site on a page with parameters. Eg, my router is set up like this:

`const router = new VueRouter({
    history : true,
    mode : "history",
    routes: [
        {
            path: "/",
            name:  "home",
            component: Home
        },
        {
            path: "/register",
            name: "register",
            component: Register,
        },
        {
            path: "/login",
            name : "login",
            component: Login,
        },
        {
            path : "/test/:id",
            name : "test",
            component: Test,
        }
    ],
});`

The "Home", "Login" and "Register" endpoints all pick-up fine if I'm logged in, and also have the $auth.user() object as expected.

However, my "Test" component doesn't have the $auth.user() component if I start on that page, or refresh while on that page, it is undefined when I console.log it.

To test this, I altered my config so that "Login" took in a parameter also, like so:

`
        {
            path: "/login/:test",
            name : "login",
            component: Login,
        },
    ],
});`

When I navigated to /login/123, the same symptoms were seen.

Is this a problem with vue-auth, or something I'm not doing right with my parameters? Any help appreciated!

**Comment by comhernandez28** [comment]
I am also having this problem
When I go to a page with params ex:
/test/:testId
I cannot access the user object.

**Comment by comhernandez28** [comment]
It seems like Vue-Auth has a problem with persisting the $auth.user() object when sent through a path such as /foo/:fooId

A workaround is to set params through other means and pass that long to /foo and then handle calling data through those params. But this is less than optimal because it requires a store to persist that state on page refreshes.

**Comment by comhernandez28** [comment]
So I spent some time testing multiple things and I think the problem is that the component is not refreshed when you navigate to a route with params. 
This information can be found here: 
https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes

I believe vue-auth has problems getting to the $auth.user() object when the component isn't actually being re rendered. 

@websanova Am I on the right track here with this issue?

**Comment by comhernandez28** [comment]
@AllFallD0wn I spent all night getting no sleep over this and found a really weird workaround. 
First of all make sure that every time you call `/foo/:id` its actually calling lifecycle methods. 

Easiest way to test is to just `console.log("component mounted")` on the `mounted() {}` lifecycle. 

Once that is done you can just do an axios call to youre user route, the one vue auth is fetching your user from. 

Then you call vue-auths `this.$auth.user(userObject);` function which can be found here: https://github.com/websanova/vue-auth/blob/master/docs/Methods.md

I'm not sure if it's the best fix but it works! Unfortunately I think you will have to use this workaround every single time you use a page with params, which is a lot for me.

**Comment by websanova** [comment]
Probably not using $auth.ready() correctly here.
