### ISSUE TITLE
$auth.token doesn't keep token in LocalStorage

### ISSUE THREAD

**Issue by Aarbel** [websanova/vue-auth#492]
$auth.token doesn't keep token in LocalStorage,

for example this code will clean the `default_auth_token` after redirect 
### How to add `rememberMe` behavior ? 
```JS
this.$auth.token('default_auth_token', new_token);
this.$router.push({ name: 'home' })
```

Thanks a lot for your help !

**Comment by patchbank** [comment]
Are you sure that it's gone just after a plain page refresh?
If yes, then it might be a browser related problem.

Maybe you have the same problem I have:
After setting a token, the authenticated and loading states and fetching the data, the website works perfectly fine. The token remains in the localStorage of the browser.
After refreshing the page, it's not sending the Authorization header to my server, which results in removing the token from the localStorage, because the server (in my case) responds with a 401.

**Comment by patchbank** [comment]
Okey, I figured it out. At least my issue (as I don't know if your issue is related to mine).

When logging in by setting the token instead of using the login function, it doesn't activate the remember feature of vue-auth, which tells vue-auth to use the saved token (basically).

Import the cookie module from vue-auth and call the remember method after you've set the token:
```javascript
import VueAuthCookie from '@websanova/vue-auth/src/lib/cookie';

// ...

// Make the auth plugin ready and then set the token + remember cookie
this.$auth.ready();
this.$auth.token(null, token);
VueAuthCookie.remember.call(this.$auth, true);

// Set vue-auth status
this.$auth.watch.loaded = true;
this.$auth.watch.authenticated = true;

// Fetch user and redirect to homepage
await this.$auth.fetch();
```
