### ISSUE TITLE
Is it possible to not fetch /auth/user after every login?

### ISSUE THREAD

**Issue by petarjs** [websanova/vue-auth#51]
Hi, I'm wondering if there's a way to turn of the request to `/auth/user` that happens after each login?

I can see it happening on this [line](https://github.com/websanova/vue-auth/blob/master/src/auth.js#L190), and I tried passing an empty object for `fetchPerform` and `fetchData` options, but it had no effect.

**Comment by websanova** [comment]
Hmm, try setting fetchData to null or empty object. Without a url I think
http will gracefully fail. I'm on holiday so can't test at the moment.

If that doesn't work I can add in a check for that next week.

**Comment by petarslovic** [comment]
Thanks for the response!

If we pass `fetchData` option as an empty object, the `fetchPerform` method indeed does an http call without a url. But this means that http service uses just the root url when making that request (e.g. `http://localhost/v1/`), which fails and the [success callback](https://github.com/websanova/vue-auth/blob/master/src/auth.js#L191) never gets called, which brakes the login functionality.

I think that the best solution would be to separate the logic of what happens in `fetchProcess` into a new method called something like `setLoginData`, as this is behaviour that should happen after a successful login:

```js
function setLoginData(data) {
    this.watch.authenticated = true;
    this.watch.loaded = true;
}
```

Now we could test if `fetchData` option exists, and not perform user fetching if it doesn't, while still getting the successful login behaviour like:

```js
function _fetchProcess(res, data) {
    this.watch.data = this.options.parseUserData.call(this, this.options._httpData.call(this, res));

    setLoginData(data);

    if (data.success) { data.success.call(this, res); }
}
```

```js
function _loginProcess(res, data) {
    var _this = this;

    __cookie.set.call(this, data.rememberMe);

    this.authenticated = null;

    if(this.options.fetchData) {
      this.options.fetchPerform.call(this, {
          success: function () {
              if (data.success) { data.success.call(this, res); }

              if (data.redirect && _this.options.check.call(_this)) {
                  _this.options._routerGo.call(_this, data.redirect);
              }
          },
      });
    } else {
      this.watch.data = {};

      setLoginData();

      if (data.redirect && _this.options.check.call(_this)) {
          _this.options._routerGo.call(_this, data.redirect);
      }
    }
}
```

Would you consider a pull request?

Enjoy your holiday! 🎉

**Comment by websanova** [comment]
Sure can do a pull request, but don't have any way to push up to npm at the
moment :p I'll be back to it Monday :-)

**Comment by petarslovic** [comment]
Oh yeah, no worries :) please check out the pull request when you get the time and tell me if there's something that needs to be updated.

**Comment by websanova** [comment]
Hmm, so we only want to disable this on login?

If the `fetchData` is set to null it would also fail to load in a few other situations:

* On refresh.
* When calling `fetch()` manually.

It this also intended? There could be two separate concerns here actually.

* Disable user fetch on login (would still occur on refresh and manual calls).
* Disable user fetch completely (but this might kill the manual fetch method).

I know it was mentioned to just set it to `null` but after thinking it over, even if disabled having the manual `fetch()` call available would still be very useful rather than having to code it in since it's connected to a few things internally.

In the end the plugin will not function without the user data there and it would need to be loaded either by `fetch()` or by manually setting `user({data})`. Not to mention setting the states internally. Really the internal `fetch()` call "SHOULD" be called at some point. Even the `check` function will always fail here since the user data is null and it can't perform any role checks.

Might help better to understand what is trying to be achieved here. So you want the user "authenticated" and that's it. Are you ever fetching the user data?

**Comment by websanova** [comment]
Ok, I've setup an initial version of this which I think works quite well and doesn't break any existing code. So you will need to disable `fetchUser` in `loginData`

~~~
Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require(@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),

    loginData: {
        fetchUser: false
    },

   ...
});
~~~

**NOTE**

* Note that this will disable fetching the user on both login and refresh.
* You can still call `fetch()` manually (preferred way) to fetch the user later on. Which will automatically trigger the watches, etc.

Also note that this change is in `v2.1.0-beta` which is the 2.x stream. This means you also need to now manually set drivers for `auth`, `http`, `router`. Please check the change log for notes.

**Comment by petarslovic** [comment]
Amazing! Yeah, my use case doesn't require fetching the user. Thanks for the throughout analysis and adding this option!

**Comment by websanova** [comment]
I think this one is good, closing off. thx again for help here :-)
