### ISSUE TITLE
$auth.check() return true before route changed after update to 3.x

### ISSUE THREAD

**Issue by zorn-v** [websanova/vue-auth#534]
After update vue-auth to 3.0.7 `$auth.check()` began to return true very early.
For example if you have layout like
```html
...
<div v-if="$auth.check()">
  Some menu
  <button @click="$auth.logout()">Logout</button>
</div>
<div v-if="$auth.ready()">
  <router-view/>
</div>
...
```
After you press login, "menu" div will be displayed before user fetched from server and you will see "login form" and "menu with logout" at the same time. But if you add role for check (like `$auth.check('user')`) it start work as before.

**Comment by zorn-v** [comment]
Seems I need to check `$auth.user()` as it return null now if user is empty.
But anyway I think current `check()` without roles works wrong now.

**Comment by websanova** [comment]
Nah, that's what $auth.ready() is for already, why would you want to
duplicate that functionality?

Not sure why you wouldn't just put the ready check around your menu to
begin with or just use it twice or use computes prop. Lots of options.

And yep, $auth.ready() returns null now if not set.

**Comment by zorn-v** [comment]
> Not sure why you wouldn't just put the ready check around your menu

`ready()` without arguments return true very early now, and because of it there is visual issues.

Check https://github.com/websanova/vue-auth/pull/535 (maybe better change `&&` to `||` there)

**Comment by websanova** [comment]
Thx for taking a better look at this.

I've made a small change as to when the actual authenticated state is updated during the login call. It was set to do it immediately after success response and not wait for the fetch call. This was actually intentional, but I see it will lead to the problem you have so I've update it to not update the state until both requests have been made successfully.

With the changes in the pull request, I don't think that's correct since really the user data should not be tied into the auth state. Sure it's a quick fix, but it can create other issues.

Let me know how this latest change works out, `3.0.0.8-beta`.

**Comment by zorn-v** [comment]
> I don't think that's correct

I too, but it worked for me :smile:

**Comment by websanova** [comment]
lol, yea beta forever. last year I was super busy, so just kind of getting back to it now. With the new version 3 release I was thinking of removing it but thought I would leave that in for a little while until little issues like the ones you've reported get sorted out. But ya, planning to remove that in a month or so and make it official :-P
