### ISSUE TITLE
What is a proper way to watch auth state ?

### ISSUE THREAD

**Issue by zorn-v** [websanova/vue-auth#566]
I want to perform some actions on auth state changed.
E.g. update some info in store, subscribe/unsubscribe to private channel on websockets etc. 
Currently I think to create component with some logic in `mounted/beforeDestroy` and add something like `<auth-watcher v-if="$auth.check()" />` in `App.vue`

But maybe there is a better way to do this ?

**Comment by websanova** [comment]
Hmm, normally I would do that with a computer/watch on the component rather than using lifecycle hooks.

For instance if you are watching check just return that in a computed prop and watch that computed prop.

You can of course fire a method in th computed prop as well but maybe that's not the best practice.

This can also be done directly in Vuex with a watch directly in there. Never really had occasion for that, but should work.

**Comment by zorn-v** [comment]
> Hmm, normally I would do that with a computed/watch on the component rather than using lifecycle hooks.

Sorry for incorrect question in title, but I mean something like "which property of $auth I should watch" )
I mean property that did not changed in future versions etc. Also maybe add such use case in docs.
I preffer to use `$auth.check()` because it is documented and I did not like use undocumented features (it can be changed without notice)

**Comment by zorn-v** [comment]
> For instance if you are watching $auth.check just return that in a computed prop and watch that computed prop.

Hmm, nice catch. Thanks

**Comment by websanova** [comment]
Well generally using internal properties should be avoided. The check method is exactly for that reason. In this case I would just use a computed prop.

**Comment by zorn-v** [comment]
Yep, I just misunderstood what you mean about computed property at first (thought you mean some internal vue-auth computed).
"Problem" solved, thanks again.
