### ISSUE TITLE
Vue3 Demo - Could not resolve dependency vue@"^3.2.0" from vue-router@4.0.13

### ISSUE THREAD

**Issue by MarcoDotNet** [websanova/vue-auth#683]
Hello, and thank you for the effort you put into this Project.

I'm a beginner with Vue and tried to run your vue3 demo, unfortunately without success.

```
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.2.0" from vue-router@4.0.13
npm ERR! node_modules/vue-router
npm ERR!   vue-router@"next" from the root project
```

It would be great if you could update the dependencies. The current last stable vue version "3.2.33" worked for me.

**Comment by tchery** [comment]
Hi.

Since Vue.js 3.2, the build tool is now Vote and no more Vue CLI.
There are some adjustments to be done to the Websanova project because it is based on Vue CLI structure. 

Check the following link to get an overview of what are the differences:
https://vueschool.io/articles/vuejs-tutorials/how-to-migrate-from-vue-cli-to-vite/

Hope this will help you.

**Comment by websanova** [comment]
Yea, just haven't got around to it yet, bit busy with work.
