### ISSUE TITLE
Catching 400 error codes return an error.

### ISSUE THREAD

**Issue by dobromir-hristov** [websanova/vue-auth#76]
I wrapped up a simple app and my Laravel API returns a 400 when my token is not valid (its by default that way). I saw that we are filtering for 401's in the `@websanova/vue-auth/drivers/http/vue-resource.1.x.js`  in the `_invalidToken` function. So I decided to override it and add a 400 to that check. That returned a `TypeError: _auth is undefined`. 
Any idea what makes it behave like that?
I also tried to add a normal interceptor and track for the 400 error my self, but then I have absolutely no access to the VM ("this" returns an empty object) so I cannot do `this.$auth.logout()` or anything. 

Frankly I have no idea where this question is suited for, here or the Vue forum. Sorry if you think this is the wrong place to ask the question.

**Comment by websanova** [comment]
Hmm, what version are you using . There is currently only a 2.x driver in
there.

https://github.com/websanova/vue-auth/tree/master/drivers/router


On Dec 23, 2016 19:56, "Dobromir Hristov" <notifications@github.com> wrote:

I wrapped up a simple app and my Laravel API returns a 400 when my token is
not valid (its by default that way). I saw that we are filtering for 401's
in the @websanova/vue-auth/drivers/http/vue-resource.1.x.js in the
_invalidToken function. So I decided to override it and add a 401 || 400.
That returned a TypeError: _auth is undefined.
Any idea what makes it behave like that?
I also tried to add a normal interceptor and track for the 400 error my
self, but then I have absolutely no access to the VM ("this" returns an
empty object) so I cannot do this.$auth.logout() or anything.

Frankly I have no idea where this question is suited for, here or the Vue
forum. Sorry if you think this is the wrong place to ask the question.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/76>, or mute the thread

**Comment by websanova** [comment]
Sry, disregard that...Was thinking Vue router....

**Comment by websanova** [comment]
Can, I see your code. HW you are overriding it?

**Comment by dobromir-hristov** [comment]
Just for the test I changed your code to check for a 400 as well, ofc I didnt leave it like that.
```js
import Vue from 'vue'
import Quasar from 'quasar'
import router from './router'
import VueResource from 'vue-resource'

Vue.router = router

Vue.use(VueResource)
Vue.http.options.root = 'http://api.terrariums.eu/api/v1'
Vue.http.interceptors.push((request, next) => {
  next((response) => {
    if (response.status === 400 && (typeof response.body !== 'undefined' && response.body.error === 'token_invalid')) {
      console.log(this)
    }
    if (response.status === 401) {
      this.$auth.logout()
    }
  })
})

Vue.use(Quasar) // Install Quasar Framework

Vue.use(require('@websanova/vue-auth'), {
  auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
  http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
  router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js')
})

Quasar.start(() => {
  /* eslint-disable no-new */
  new Vue({
    el: '#q-app',
    router,
    render: h => h(require('./App'))
  })
})
```

This is my main.js.  I have a simple interceptor and it returns an empty object every time.

**Comment by websanova** [comment]
So the console.log is firing there?

Can you console.log(the.$auth).

**Comment by dobromir-hristov** [comment]
That's the problem, `this` is just an empty object. I'm pretty sure this is not a problem with vue-auth but I don't know how to proceed. When my server returns a 400 error, I don't want to catch it on EVERY request I do, I wanted to have a global catch all piece.

**Comment by websanova** [comment]
Ah, ok. Ya, so this is just a Vue thing. It's because the app has not been instantiated yet at that point.

I've had this issue before and I got around it by using the `created` (or `mounted` for 2.0) method in the root component.

```
        created() {
            console.log('created');

            Vue.http.interceptors.push((request, next) => {
              next((response) => {
                  console.log(this);
                  console.log(this.$auth);
              })
            })
        },
```

**Comment by websanova** [comment]
I've also made some fixes here so that the default 401 catch works properly in `v2.3.3-beta`
