### ISSUE TITLE
why is it redirecting to "/" on failed login?

### ISSUE THREAD

**Issue by rusenask** [websanova/vue-auth#80]
I am getting some troubles in failed auth handling, not sure how it configure it. Every time when a user fails to input correct credentials - auth routes it to "/", how to change this behaviour?

edit: this is login function. I can see this " console.log('error ' + this.context);" in the logs, but it always redirects to "/". 
```
this.$auth.login({
                    body: this.data.body,
                    rememberMe: this.data.rememberMe,
                    redirect: {name: 'buckets'},
                    fetchUser: false,
                    success() {
                        this.buttonSubmitLoading = false;
                        console.log('success ' + this.context);
                    },
                    error(res) {
                        this.buttonSubmitLoading = false;
                        console.log('error ' + this.context);
                        this.error = res.data;
                    }
                });
```

**Comment by websanova** [comment]
I'm really not sure how this can be happening for you unless you have some other interceptors involved.

**Comment by rusenask** [comment]
maybe it's because I still add standard vue router?

```
import VueResource from 'vue-resource';
import VueRouter from 'vue-router'

Vue.use(VueResource)
Vue.use(VueRouter)

```

or this should be enough?
```
// Vue Auth
Vue.use(require('@websanova/vue-auth'), {
    auth: require('@websanova/vue-auth/drivers/auth/bearer.js'),
    http: require('@websanova/vue-auth/drivers/http/vue-resource.1.x.js'),
    router: require('@websanova/vue-auth/drivers/router/vue-router.2.x.js'),
    rolesVar: 'role',
});
```

**Comment by websanova** [comment]
not sure how that is working at all. YOu should be seeing an error for
Vue.router missing.

**Comment by rusenask** [comment]
My app.js looks like https://github.com/websanova/vue-auth/blob/master/2.x.demo/src/app.js except I also have these in the top:

```
import Vue from 'vue';
import VueRouter from 'vue-router';
import VueResource from 'vue-resource';
import Components from './components/_index';

Vue.use(VueResource)
Vue.use(VueRouter)
```

without router defined I get missing router error.

**Comment by websanova** [comment]
Right, so what's your issue exactly??

**Comment by rusenask** [comment]
on failed login, i.e. if user entered wrong credentials he always gets redirected to "/" instead of remaining in the same "/login" page and seeing an error. I guess there is a config for that, right?

**Comment by websanova** [comment]
No, it shouldn't be doing anything. Have you added any interceptors to your
app?

**Comment by wcarron27** [comment]
I think what might be happening is that your Vue.js application might be redirecting all routes to '/' in your vue-router config. Happened to me a while back, can't remember for sure, though.

**Comment by websanova** [comment]
But this is happening for incorrect credentials, so it shouldn't be hitting
the router at all. There is a redirect somewhere.

I just realized. Are you returning a 401 on your failed login. There is an
intercept for that in _invalidToken function.

**Comment by rusenask** [comment]
Yes, 401 on failed login. Would it make sense on interceptor to check request status codes only for authenticated requests?

**Comment by websanova** [comment]
Hmm, well you are correct in sending the 401.

From Wikipedia... "Similar to 403 Forbidden, but specifically for use when
authentication is required and has failed or has not yet been provided. The
response must include a WWW-Authenticate header field containing a
challenge applicable to the requested resource. ".

Seems I fuged that up. It should be checking for a 403 not a 401 there. I
will update this shortly and let you know.


On Jan 3, 2017 15:41, "Karolis Rusenas" <notifications@github.com> wrote:

Yes, 401 on failed login. Would it make sense on interceptor to check
request status codes only for authenticated requests?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/80#issuecomment-270069662>,
or mute the thread

**Comment by websanova** [comment]
Ok, this should be fine now in `v2.3.4-beta`. So basically, it's as you said previously. It only checks for invalid tokens if the user is already logged in.

Otherwise the token check is still set for 401. This seems more accurate since forbidden doesn't indicate that there is anything actually wrong with the token. Where 401 is more that the credentials themselves are actually invalid which is what we're looking for in this case.

Thx, for sticking through this, it's a nice catch :-)
