### ISSUE TITLE
Login redirect to where the user came from

### ISSUE THREAD

**Issue by shakee93** [websanova/vue-auth#85]
this is a great package thank you for the great work. I have searched for this feature on your repo and i have tried to reach this via vue router. unfortunately it didnt work maybe because it is been handled by vue-auth.

here is the scenario

this route has `auth true` on router
http://example.dev/challenges

when i try to access this it will redirect to login page. what i need is when user logs in redirect to the page where he has come from. i have tried to use the **vue-router `beforeEach`** method it works well when i run it directly **(without refreshing or from direct url)** when i try from the direct url. it breaks and gives a different `from `path.

it would be nice if we have a callback or something on the `authRedirect `method with the data. or if you have any other solution for this please let me know.

thanks

**Comment by websanova** [comment]
I see what you mean. I will test this out tmr.

**Comment by websanova** [comment]
Ok, so this is actually a bit tricky to do from the plugin. Since it's intercepting the page there is never a proper "from" transition set. Also because the plugin doesn't rely on on the root component being set it means there is no instance when accessing the beforeEach method in the plugin.

However what I can do is to track an internal transition within the plugin. I've added a method for this called `$auth.transition()`. Make sure to get the latest `v2.4.0-beta`

I've added some docs here: https://github.com/websanova/vue-auth#transition

In the login page you could then do something like:

~~~
login() {
    this.$auth.login({
        ...
        redirect: this.$route.query.redirect_url || '/account'
    });
 }
~~~

**Comment by shakee93** [comment]
Thank you for the update. btw i am using vue2 this is not available in the beforeEach or in component injection beforeRouteEnter. is there any workaround for this.

and it would be cool. if we can have it as parameter on login something like "redirectToRequested : true" or something. so vue-auth will take care of it in the background.

**Comment by websanova** [comment]
I thought about that, but there will likely be some exceptions and other
variables.

**Comment by shakee93** [comment]
I missed this post. it would be nice if you have a workaround for this out of the box. most probably laravel auth works this way it will be much cooler. the caveats are okey by the way :D
